### ISSUE TITLE
informationUri not always populated by scanners (semgrep)

### ISSUE THREAD

**Issue by Gby56** [HollowMan6/sarif4reviewdog#6]
https://github.com/HollowMan6/sarif4reviewdog/blob/70fd54da0c00b0e4b807de395cc60b42e34c5453/convert.py#L14C8-L14C8

Seems like that key in the dict doesn't exist for semgrep SARIF, so it can't be converted.
Could we put a default value `""` or something configurable via the `with` inputs of the action maybe ?

**Comment by HollowMan6** [comment]
Should be fixed in https://github.com/HollowMan6/sarif4reviewdog/releases/tag/v1.0.1

Thanks for raising this issue!
